name: Docusaurus Firebase Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: GitHub Action for Firebase
        run: npm install -g firebase-tools && cd documentation && yarn && yarn build && firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
